name: DeluxeCoinflip
version: '${version}'
main: net.zithium.deluxecoinflip.DeluxeCoinflipPlugin
authors: [ ItsLewizzz, ItzSave, ItsSimplyLeo, hyperion ]
api-version: 1.19
folia-supported: true

softdepend:
  - PlaceholderAPI
  - Vault
  - TokenEnchant
  - TokenManager
  - EssentialsX
  - ZithiumMobcoins

permissions:
  coinflip.admin:
    default: op
